// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include <gtest/gtest.h>

#include "common_shared/cryptography/hash-functions.h"

void hexCharToInt(const char ch, uint8_t& res)
{
	if (ch >= '0' && ch <= '9')
	{
		res = ch - '0';
		return;
	}

	if (ch >= 'A' && ch <= 'F')
	{
		res = 10 + (ch - 'A');
		return;
	}

	if (ch >= 'a' && ch <= 'f')
	{
		res = 10 + (ch - 'a');
		return;
	}

	FAIL();
}

void assertEven(size_t n)
{
	ASSERT_EQ(n % 2, size_t(0)) << "Only whole bytes expected in hex, pad with 0";
}

std::vector<uint8_t> hexToBytes(const std::string_view inString)
{
	std::vector<uint8_t> outVector;
	assertEven(inString.size());
	outVector.resize(inString.size() / 2);
	for (size_t i = 0; i < outVector.size(); ++i)
	{
		uint8_t v1;
		uint8_t v2;
		hexCharToInt(inString[i * 2], v1);
		hexCharToInt(inString[i * 2 + 1], v2);
		outVector[i] = (v1 << 4) | v2;
	}
	return outVector;
}

std::vector<uint8_t> strToBytes(const std::string_view inString)
{
	std::vector<uint8_t> outVector;
	outVector.reserve(inString.size());
	for (const char ch : inString)
	{
		outVector.push_back(static_cast<uint8_t>(ch));
	}
	return outVector;
}

template<size_t Size>
void vectorToArray(const std::span<const uint8_t> inVector, std::array<uint8_t, Size>& outArray)
{
	ASSERT_EQ(inVector.size(), outArray.size());
	for (size_t i = 0; i < outArray.size(); ++i)
	{
		outArray[i] = inVector[i];
	}
}

static void testHmac_blake2b(const std::span<const uint8_t> keyVec, const std::span<const uint8_t> dataVec, const std::span<const uint8_t> expectedVec)
{
	Cryptography::HashResult key;
	vectorToArray(keyVec, key.raw);

	std::array<uint8_t, Cryptography::HASHLEN> expectedResult;
	vectorToArray(expectedVec, expectedResult);

	Cryptography::HashResult actualResult;
	Cryptography::HMAC_blake2b(key, dataVec, actualResult);

	EXPECT_EQ(actualResult.raw, expectedResult);
}

TEST(CryptographyHashFunctions, HmacTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b
	// test vecrtors are based on https://www.ietf.org/rfc/rfc2104.txt

	testHmac_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		strToBytes("Hi there!"),
		hexToBytes("f35293c25cbbec911339599b79e960a20b6439209c5570ef5e0607834163abf0")
	);

	testHmac_blake2b(
		// compared to the test from https://www.ietf.org/rfc/rfc2104.txt
		// we locked the function to work only with HASHLEN size of keys
		// so pad it with zeros
		strToBytes("Jefe0000000000000000000000000000"),
		strToBytes("what do ya want for nothing?"),
		hexToBytes("46259ce09762c902522c33734707ce0392dcc73b47f54da314fd72f8c89cbd86")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("09553c3e8fbaab43a0230549fefd0d33295ed0f723b0d1f5d40419b14c7d53a4")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("b2d5a1cdc52396c85d3b1ce5ce85267fe07f8c67a278bd9a74b0e793173fc34d")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("5e917f61d3b39d0a21b6e72630f2fff5fec34c3c354a3a8fdd3a1202d170d6a4")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes(""),
		hexToBytes("d1b06a3fbc3db187a60b894572b4ab52e6e16217c20a9e3f4d09eec6c0c2b22a")
	);
}
