// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include "tests/helper_utils.h"
#include <gtest/gtest.h>

#include "common_shared/cryptography/noise/internal/utils.h"

static void testInitializeSymmetric(const std::string_view protocolName, const std::span<const uint8_t> expectedVec)
{
	std::array<uint8_t, Cryptography::HASHLEN> expectedResult;
	vectorToArray(expectedVec, expectedResult);

	Noise::SymmetricState symmetricState = Noise::Utils::initializeSymmetric(protocolName);

	// during the initialization, ck and h are equal
	EXPECT_EQ(symmetricState.chainingKey.raw, expectedResult);
	EXPECT_EQ(symmetricState.handshakeHash.raw, expectedResult);
}

TEST(CryptographyNoiseUtils, initializeSymmetric_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	testInitializeSymmetric("Noise_XX_25519_AESGCM_BLAKE2b", hexToBytes("4e6f6973655f58585f32353531395f41455347434d5f424c414b453262000000"));
	testInitializeSymmetric("Noise_N_25519_ChaChaPoly_BLAKE2b", hexToBytes("4e6f6973655f4e5f32353531395f436861436861506f6c795f424c414b453262"));
	testInitializeSymmetric("Noise_IK_448_ChaChaPoly_BLAKE2b", hexToBytes("4e6f6973655f494b5f3434385f436861436861506f6c795f424c414b45326200"));
	testInitializeSymmetric("Noise_KK_25519_ChaChaPoly_BLAKE2b", hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"));
	testInitializeSymmetric("Noise_XX_25519_ChaChaPoly_BLAKE2b", hexToBytes("c87e5b264ee3f8105e645e7d91c71309ce189793b0f63ec7b325ff1e88af4d39"));
	testInitializeSymmetric("Noise_XXfallback+psk0_25519_AESGCM_BLAKE2b", hexToBytes("d9f8b10f90d7f7395ba28f1f45de49104cd9fab6e56f17bbd66cbc8a875e6b40"));
}

TEST(CryptographyNoiseUtils, mixHash_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	Noise::SymmetricState symmetricState;
	vectorToArray(hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"), symmetricState.handshakeHash.raw);

	Noise::Utils::mixHash(strToBytes("data to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("c4fc1b79ee7f85c140887dac0e1c165f1b632e7ef901722f64820033c9061a03")), symmetricState.handshakeHash.raw);
	Noise::Utils::mixHash(strToBytes("more data to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("8697334e07b527b6bb0d697a0e1ee1e68dac8a81a6c1f80435299e066e1ece94")), symmetricState.handshakeHash.raw);
	Noise::Utils::mixHash(strToBytes("even more data to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("14aa993c4bb8cfc0893ac0be584bc41e48537c67cd31e0c0659ff18235c7cdd3")), symmetricState.handshakeHash.raw);
}

TEST(CryptographyNoiseUtils, mixKey_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	Noise::SymmetricState symmetricState;
	vectorToArray(hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"), symmetricState.handshakeHash.raw);
	vectorToArray(hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"), symmetricState.chainingKey.raw);
	symmetricState.cipherState = Noise::CipherStateHandshake{};

	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd")), symmetricState.chainingKey.raw);
	EXPECT_EQ(vectorToArray<Cryptography::CipherKeySize>(hexToBytes("0000000000000000000000000000000000000000000000000000000000000000")), symmetricState.cipherState->cipherKey.raw);
	EXPECT_EQ(static_cast<uint64_t>(0), symmetricState.cipherState->nonce);
	Noise::Utils::mixKey(strToBytes("input key material to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("acabea2d7b60b142822b9fdfe854be8b79d28b7629d98b0843055191bf447752")), symmetricState.chainingKey.raw);
	EXPECT_EQ(vectorToArray<Cryptography::CipherKeySize>(hexToBytes("48c08419f44eb9b1dcd468642d0e7f9edd5621fcd31d83dbb039c33c840dcce9")), symmetricState.cipherState->cipherKey.raw);
	EXPECT_EQ(static_cast<uint64_t>(0), symmetricState.cipherState->nonce);
	Noise::Utils::mixKey(strToBytes("more input key material to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("4609e704ad389aa726a889aa36111f361ff7f306fdeaf89640eda13d5b798a51")), symmetricState.chainingKey.raw);
	EXPECT_EQ(vectorToArray<Cryptography::CipherKeySize>(hexToBytes("297b6973e958d7ed70038eecc073dd90a7547f56c18030e913aa3d99a53c8e91")), symmetricState.cipherState->cipherKey.raw);
	EXPECT_EQ(static_cast<uint64_t>(0), symmetricState.cipherState->nonce);
	Noise::Utils::mixKey(strToBytes("even more input key material to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("d560b1dd54852ff8c57cb22bd656880334b7db1f36a78cbabc5a53ccbae3d8ea")), symmetricState.chainingKey.raw);
	EXPECT_EQ(vectorToArray<Cryptography::CipherKeySize>(hexToBytes("ef720e03cd1a6447cb6dc913ec958dbd95a4e5b053267caf497d78360c0c1381")), symmetricState.cipherState->cipherKey.raw);
	EXPECT_EQ(static_cast<uint64_t>(0), symmetricState.cipherState->nonce);
}

TEST(CryptographyNoiseUtils, split_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	Noise::SymmetricState symmetricState;
	vectorToArray(hexToBytes("d560b1dd54852ff8c57cb22bd656880334b7db1f36a78cbabc5a53ccbae3d8ea"), symmetricState.chainingKey.raw);
	vectorToArray(hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"), symmetricState.handshakeHash.raw);

	Noise::CipherStateSending c1;
	Noise::CipherStateReceiving c2;
	Noise::Utils::split(symmetricState, c1, c2, Noise::Utils::HandshakeRole::Initiator);

	EXPECT_EQ(vectorToArray<Cryptography::CipherKeySize>(hexToBytes("b0018b79868da55dd509bde6b2d69eef0fb3ddb6c23ac89ac7d636a0128c192a")), c1.cipherKey.raw);
	EXPECT_EQ(c1.nonce, static_cast<uint64_t>(0));

	EXPECT_EQ(vectorToArray<Cryptography::CipherKeySize>(hexToBytes("387ecd2fbc53ea90c8e5875fb5189e8fabfd98471361cb472ac9d42d9063265e")), c2.cipherKey.raw);
	EXPECT_EQ(c2.nonce, static_cast<uint64_t>(0));
}

TEST(CryptographyNoiseUtils, writeDataToBuffer_writeWithinBuffer_succeeds)
{
	std::array<std::byte, 30> buffer = {};

	size_t cursor = 0;

	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("0b0a0c"), buffer, cursor), 0);
	EXPECT_EQ(buffer, vectorToByteArray<30>(hexToBytes("0b0a0c000000000000000000000000000000000000000000000000000000")));
	EXPECT_EQ(cursor, static_cast<size_t>(3));

	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("00112233445566778899AABBCCDDEEFF"), buffer, cursor), 0);
	EXPECT_EQ(buffer, vectorToByteArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFF0000000000000000000000")));
	EXPECT_EQ(cursor, static_cast<size_t>(19));

	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes(""), buffer, cursor), 0);
	EXPECT_EQ(buffer, vectorToByteArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFF0000000000000000000000")));
	EXPECT_EQ(cursor, static_cast<size_t>(19));

	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("FEDCBA9876543210AABBCC"), buffer, cursor), 0);
	EXPECT_EQ(buffer, vectorToByteArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFFFEDCBA9876543210AABBCC")));
	EXPECT_EQ(cursor, static_cast<size_t>(30));

	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes(""), buffer, cursor), 0);
	EXPECT_EQ(buffer, vectorToByteArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFFFEDCBA9876543210AABBCC")));
	EXPECT_EQ(cursor, static_cast<size_t>(30));
}

TEST(CryptographyNoiseUtils, writeDataToBuffer_writeBeyondBuffer_fails)
{
	std::array<std::byte, 8> buffer = {};

	size_t cursor = 0;

	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("001122334455667788"), buffer, cursor), -1);

	cursor = 7;
	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("0011"), buffer, cursor), -1);

	cursor = 8;
	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("00"), buffer, cursor), -1);

	cursor = 9;
	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes(""), buffer, cursor), -1);

	cursor = 20000;
	ASSERT_EQ(Noise::Utils::writeDataToBuffer(hexToBytes("00"), buffer, cursor), -1);
}

TEST(CryptographyNoiseUtils, readDataFromBuffer_readWithinBuffer_succeeds)
{
	const std::array<std::byte, 30> buffer = vectorToByteArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFFFEDCBA9876543210AABBCC"));

	size_t cursor = 0;
	std::array<uint8_t, 30> readData = {};

	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin(), readData.begin() + 3), cursor), 0);
	EXPECT_EQ(readData, vectorToArray<30>(hexToBytes("0b0a0c000000000000000000000000000000000000000000000000000000")));
	EXPECT_EQ(cursor, static_cast<size_t>(3));

	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin() + 3, readData.begin() + 19), cursor), 0);
	EXPECT_EQ(readData, vectorToArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFF0000000000000000000000")));
	EXPECT_EQ(cursor, static_cast<size_t>(19));

	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin() + 19, readData.begin() + 19), cursor), 0);
	EXPECT_EQ(readData, vectorToArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFF0000000000000000000000")));
	EXPECT_EQ(cursor, static_cast<size_t>(19));

	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin() + 19, readData.begin() + 30), cursor), 0);
	EXPECT_EQ(readData, vectorToArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFFFEDCBA9876543210AABBCC")));
	EXPECT_EQ(cursor, static_cast<size_t>(30));

	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin() + 30, readData.begin() + 30), cursor), 0);
	EXPECT_EQ(readData, vectorToArray<30>(hexToBytes("0b0a0c00112233445566778899AABBCCDDEEFFFEDCBA9876543210AABBCC")));
	EXPECT_EQ(cursor, static_cast<size_t>(30));

	// make sure we don't write anything before and after the provided buffer
	std::array<uint8_t, 8> zeroPaddedBuffer = {};
	cursor = 5;
	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(zeroPaddedBuffer.begin() + 2, zeroPaddedBuffer.begin() + 6), cursor), 0);
	EXPECT_EQ(zeroPaddedBuffer, vectorToArray<8>(hexToBytes("0000223344550000")));
	EXPECT_EQ(cursor, static_cast<size_t>(9));

	std::array<uint8_t, 8> onePaddedBuffer = vectorToArray<8>(hexToBytes("FFFFFFFFFFFFFFFF"));
	cursor = 5;
	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(onePaddedBuffer.begin() + 2, onePaddedBuffer.begin() + 6), cursor), 0);
	EXPECT_EQ(onePaddedBuffer, vectorToArray<8>(hexToBytes("FFFF22334455FFFF")));
	EXPECT_EQ(cursor, static_cast<size_t>(9));
}

TEST(CryptographyNoiseUtils, readDataFromBuffer_readBeyondBuffer_fails)
{
	const std::array<std::byte, 8> buffer = {};
	size_t cursor = 0;

	std::array<uint8_t, 9> readData = {};

	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, readData, cursor), -1);

	cursor = 7;
	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin(), readData.begin() + 2), cursor), -1);

	cursor = 8;
	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin(), readData.begin() + 1), cursor), -1);

	cursor = 9;
	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin(), readData.begin() + 0), cursor), -1);

	cursor = 20000;
	ASSERT_EQ(Noise::Utils::readDataFromBuffer(buffer, std::span(readData.begin(), readData.begin() + 1), cursor), -1);
}
