// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include "tests/helper_utils.h"
#include <gtest/gtest.h>

#include "common_shared/cryptography/noise/utils.h"

static void testInitialideSymmetric(const std::string_view protocolName, const std::span<const uint8_t> expectedVec)
{
	std::array<uint8_t, Cryptography::HASHLEN> expectedResult;
	vectorToArray(expectedVec, expectedResult);

	Noise::SymmetricState symmetricState = Noise::Utils::initializeSymmetric(protocolName);

	// during the initialization, ck and h are equal
	EXPECT_EQ(symmetricState.chainingKey.raw, expectedResult);
	EXPECT_EQ(symmetricState.handshakeHash.raw, expectedResult);
}

TEST(CryptographyNoiseUtils, initializeSymmetric_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	testInitialideSymmetric("Noise_XX_25519_AESGCM_BLAKE2b", hexToBytes("4e6f6973655f58585f32353531395f41455347434d5f424c414b453262000000"));
	testInitialideSymmetric("Noise_N_25519_ChaChaPoly_BLAKE2b", hexToBytes("4e6f6973655f4e5f32353531395f436861436861506f6c795f424c414b453262"));
	testInitialideSymmetric("Noise_IK_448_ChaChaPoly_BLAKE2b", hexToBytes("4e6f6973655f494b5f3434385f436861436861506f6c795f424c414b45326200"));
	testInitialideSymmetric("Noise_KK_25519_ChaChaPoly_BLAKE2b", hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"));
	testInitialideSymmetric("Noise_XX_25519_ChaChaPoly_BLAKE2b", hexToBytes("c87e5b264ee3f8105e645e7d91c71309ce189793b0f63ec7b325ff1e88af4d39"));
	testInitialideSymmetric("Noise_XXfallback+psk0_25519_AESGCM_BLAKE2b", hexToBytes("d9f8b10f90d7f7395ba28f1f45de49104cd9fab6e56f17bbd66cbc8a875e6b40"));
}

TEST(CryptographyNoiseUtils, mixHash_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	Noise::SymmetricState symmetricState;
	vectorToArray(hexToBytes("cbdcafb819b0fbe08072ecb231de23aa047541bcbcf405a5ee30edddd29912dd"), symmetricState.handshakeHash.raw);

	Noise::Utils::mixHash(strToBytes("data to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("c4fc1b79ee7f85c140887dac0e1c165f1b632e7ef901722f64820033c9061a03")), symmetricState.handshakeHash.raw);
	Noise::Utils::mixHash(strToBytes("more data to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("8697334e07b527b6bb0d697a0e1ee1e68dac8a81a6c1f80435299e066e1ece94")), symmetricState.handshakeHash.raw);
	Noise::Utils::mixHash(strToBytes("even more data to mix"), symmetricState);
	EXPECT_EQ(vectorToArray<Cryptography::HASHLEN>(hexToBytes("14aa993c4bb8cfc0893ac0be584bc41e48537c67cd31e0c0659ff18235c7cdd3")), symmetricState.handshakeHash.raw);
}
