// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include "tests/helper_utils.h"
#include <gtest/gtest.h>

#include "common_shared/cryptography/primitives/cipher_functions.h"
#include "common_shared/cryptography/utils/random.h"

TEST(CryptographyCipherFunctions, chacha20poly1305_roundripTest)
{
	const std::string plaintextStr = "This is the plaintext";

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"), cipherKey.raw);

	Cryptography::Nonce nonce = 0x1234567890ABCDEF;

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("BBBBBBBB"));

	const Cryptography::DynByteSequence plaintext = Cryptography::DynByteSequence::fromVector(strToBytes(plaintextStr));

	Cryptography::DynByteSequence ciphertext;
	Cryptography::encrypt_chacha20poly1305(cipherKey, nonce, associatedData, plaintext, ciphertext);

	Cryptography::DynByteSequence resultPlaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, resultPlaintext);
	ASSERT_EQ(res, 0);

	EXPECT_EQ(resultPlaintext.raw, strToBytes(plaintextStr));
}

TEST(CryptographyCipherFunctions, chacha20poly1305_roundripRandomTest)
{
	const std::string plaintextStr = "This is the plaintext";

	Cryptography::CipherKey cipherKey;
	Cryptography::fillWithRandomBytes(cipherKey.raw);

	Cryptography::Nonce nonce;
	Cryptography::fillWithRandomBytes(std::span(std::bit_cast<uint8_t*>(&nonce), sizeof(nonce)));

	std::vector<uint8_t> associatedDataRaw;
	associatedDataRaw.resize(20);
	Cryptography::fillWithRandomBytes(associatedDataRaw);
	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(std::move(associatedDataRaw));

	const Cryptography::DynByteSequence plaintext = Cryptography::DynByteSequence::fromVector(strToBytes(plaintextStr));

	Cryptography::DynByteSequence ciphertext;
	Cryptography::encrypt_chacha20poly1305(cipherKey, nonce, associatedData, plaintext, ciphertext);

	Cryptography::DynByteSequence resultPlaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, resultPlaintext);
	ASSERT_EQ(res, 0);

	EXPECT_EQ(resultPlaintext.raw, strToBytes(plaintextStr));
}

TEST(CryptographyCipherFunctions, chacha20poly1305_encryptTest)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	const std::string plaintextStr = "text to encrypt";

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0123456789;

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("000102030405060708090a0b0c0d0e0f"));

	const Cryptography::DynByteSequence plaintext = Cryptography::DynByteSequence::fromVector(strToBytes(plaintextStr));

	Cryptography::DynByteSequence ciphertext;
	Cryptography::encrypt_chacha20poly1305(cipherKey, nonce, associatedData, plaintext, ciphertext);

	std::vector<uint8_t> expectedResult = hexToBytes("4b97a0b99cbe4e9316840e89792351e3572ee8c32d1fa534a1e3f9d0bd7093");

	EXPECT_EQ(expectedResult, ciphertext.raw);
}

TEST(CryptographyCipherFunctions, chacha20poly1305_decryptTest_correct)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("101112131415161718191a1b1c1d1e1f000102030405060708090a0b0c0d0e0f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0123456789;

	Cryptography::DynByteSequence ciphertext = Cryptography::DynByteSequence::fromVector(hexToBytes("81a31e0ca246ecee4e8dc559ad8cf5193e1e04fc8b83b5702da4b9de13e2c5"));

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("08090a0b0c0d0e0f0001020304050607"));

	Cryptography::DynByteSequence plaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, plaintext);
	ASSERT_EQ(res, 0);

	std::vector<uint8_t> expectedResult = strToBytes("text to decrypt");
	EXPECT_EQ(expectedResult, plaintext.raw);
}

TEST(CryptographyCipherFunctions, chacha20poly1305_decryptTest_wrongMac)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("101112131415161718191a1b1c1d1e1f000102030405060708090a0b0c0d0e0f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0123456789;

	Cryptography::DynByteSequence ciphertext = Cryptography::DynByteSequence::fromVector(hexToBytes("81a31e0ca246ecee4e8dc559ad8cf5193e1e04fc8b83b5702da4b9da13e2c5"));

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("08090a0b0c0d0e0f0001020304050607"));

	Cryptography::DynByteSequence plaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, plaintext);
	ASSERT_EQ(res, -1);
}

TEST(CryptographyCipherFunctions, chacha20poly1305_decryptTest_corruptedCiphertext)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("101112131415161718191a1b1c1d1e1f000102030405060708090a0b0c0d0e0f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0123456789;

	Cryptography::DynByteSequence ciphertext = Cryptography::DynByteSequence::fromVector(hexToBytes("81a31e0ca236ecee4e8dc559ad8cf5193e1e04fc8b83b5702da4b9de13e2c5"));

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("08090a0b0c0d0e0f0001020304050607"));

	Cryptography::DynByteSequence plaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, plaintext);
	ASSERT_EQ(res, -1);
}

TEST(CryptographyCipherFunctions, chacha20poly1305_decryptTest_wrongAD)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("101112131415161718191a1b1c1d1e1f000102030405060708090a0b0c0d0e0f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0123456789;

	Cryptography::DynByteSequence ciphertext = Cryptography::DynByteSequence::fromVector(hexToBytes("81a31e0ca246ecee4e8dc559ad8cf5193e1e04fc8b83b5702da4b9de13e2c5"));

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("08090a0b0c0d0e0f0001020304050609"));

	Cryptography::DynByteSequence plaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, plaintext);
	ASSERT_EQ(res, -1);
}

TEST(CryptographyCipherFunctions, chacha20poly1305_decryptTest_wrongKey)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("101112131415161718191a1b1c1d1e1f000102030305060708090a0b0c0d0e0f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0123456789;

	Cryptography::DynByteSequence ciphertext = Cryptography::DynByteSequence::fromVector(hexToBytes("81a31e0ca246ecee4e8dc559ad8cf5193e1e04fc8b83b5702da4b9de13e2c5"));

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("08090a0b0c0d0e0f0001020304050607"));

	Cryptography::DynByteSequence plaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, plaintext);
	ASSERT_EQ(res, -1);
}

TEST(CryptographyCipherFunctions, chacha20poly1305_decryptTest_wrongNonce)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::CipherKey cipherKey;
	vectorToArray(hexToBytes("101112131415161718191a1b1c1d1e1f000102030405060708090a0b0c0d0e0f"), cipherKey.raw);

	Cryptography::Nonce nonce = 0xABCDEF0113456789;

	Cryptography::DynByteSequence ciphertext = Cryptography::DynByteSequence::fromVector(hexToBytes("81a31e0ca246ecee4e8dc559ad8cf5193e1e04fc8b83b5702da4b9de13e2c5"));

	const Cryptography::DynByteSequence associatedData = Cryptography::DynByteSequence::fromVector(hexToBytes("08090a0b0c0d0e0f0001020304050607"));

	Cryptography::DynByteSequence plaintext;
	const int res = Cryptography::decrypt_chacha20poly1305(cipherKey, nonce, associatedData, ciphertext, plaintext);
	ASSERT_EQ(res, -1);
}
