// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include "tests/helper_utils.h"
#include <gtest/gtest.h>

#include "common_shared/cryptography/primitives/dh_functions.h"

TEST(CryptographyDhFunctions, DhX25519_randomTest)
{
	Cryptography::Keypair keys1 = Cryptography::generateKeypair_x25519();
	Cryptography::Keypair keys2 = Cryptography::generateKeypair_x25519();
	Cryptography::DhResult dhResult1 = Cryptography::diffieHellman_x25519(keys1.secretKey, keys2.publicKey);
	Cryptography::DhResult dhResult2 = Cryptography::diffieHellman_x25519(keys2.secretKey, keys1.publicKey);

	EXPECT_EQ(dhResult1.raw, dhResult2.raw);
}

TEST(CryptographyDhFunctions, DhX25519_test)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com

	Cryptography::Keypair keys1;
	vectorToArray(hexToBytes("170EED9741A0A1B43382CDD8F21449CF9762F9D61CBD4AE7DC9F8B17DB03371B"), keys1.publicKey.raw);
	vectorToArray(hexToBytes("DA3A44AFB3048F51484F54B38A56522BBEAB0E315F1DEE07A4A54DF4F0DA7A20"), keys1.secretKey.raw);
	Cryptography::Keypair keys2;
	vectorToArray(hexToBytes("BD918676BB3C2657A264CC1047601AD931B9FB0D5EC42E688EE7B06CE077A777"), keys2.publicKey.raw);
	vectorToArray(hexToBytes("D2EC0792480DD0EFE2850CE84C9D367202E0FB67FE462314C7A9F94ED3911F73"), keys2.secretKey.raw);

	std::array<std::byte, Cryptography::DHLEN> expectedResult = {};
	vectorToArray(hexToBytes("37266b1796b20191001d0a7b46cef587deb1f7e7b73e26d764314113ad3b4c28"), expectedResult);

	Cryptography::DhResult dhResult1 = Cryptography::diffieHellman_x25519(keys1.secretKey, keys2.publicKey);
	Cryptography::DhResult dhResult2 = Cryptography::diffieHellman_x25519(keys2.secretKey, keys1.publicKey);

	EXPECT_EQ(dhResult1.raw, expectedResult);
	EXPECT_EQ(dhResult2.raw, expectedResult);
}
