// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include "tests/helper_utils.h"
#include <gtest/gtest.h>

#include "common_shared/cryptography/primitives/hash_functions.h"

static void testHash_blake2b(const std::span<const std::byte> dataVec, const std::span<const std::byte> expectedHashVec)
{
	std::array<std::byte, Cryptography::HASHLEN> expectedResult = {};
	vectorToArray(expectedHashVec, expectedResult);

	Cryptography::HashResult actualResult;
	Cryptography::hash_blake2b(dataVec, actualResult);

	EXPECT_EQ(actualResult.raw, expectedResult);
}

static void testHashWithContext_blake2b(const std::span<const std::byte> contextVec, const std::span<const std::byte> dataVec, const std::span<const std::byte> expectedHashVec)
{
	std::array<std::byte, Cryptography::HASHLEN> expectedResult = vectorToArray<Cryptography::HASHLEN>(expectedHashVec);

	Cryptography::HashResult actualResult;
	Cryptography::hashWithContext_blake2b(contextVec, dataVec, actualResult);

	EXPECT_EQ(actualResult.raw, expectedResult);
}

static void testHmac_blake2b(const std::span<const std::byte> keyVec, const std::span<const std::byte> dataVec, const std::span<const std::byte> expectedVec)
{
	Cryptography::HashResult key;
	vectorToArray(keyVec, key.raw);

	std::array<std::byte, Cryptography::HASHLEN> expectedResult = {};
	vectorToArray(expectedVec, expectedResult);

	Cryptography::HashResult actualResult;
	Cryptography::HMAC_blake2b(key, dataVec, actualResult);

	EXPECT_EQ(actualResult.raw, expectedResult);
}

static void testHkdf_blake2b(std::vector<std::byte>&& chainingKeyVec, std::vector<std::byte>&& inputKeyMaterial, int numOutputs, std::vector<std::byte>&& expected1Vec, std::optional<std::vector<std::byte>>&& expected2Vec, std::optional<std::vector<std::byte>>&& expected3Vec)
{
	Cryptography::HashResult chainingKey;
	vectorToArray(chainingKeyVec, chainingKey.raw);

	std::array<std::byte, Cryptography::HASHLEN> expectedResult1 = {};
	vectorToArray(expected1Vec, expectedResult1);
	std::array<std::byte, Cryptography::HASHLEN> expectedResult2 = {};
	std::array<std::byte, Cryptography::HASHLEN> expectedResult3 = {};
	if (expected2Vec.has_value())
	{
		vectorToArray(*expected2Vec, expectedResult2);
	}

	if (expected3Vec.has_value())
	{
		vectorToArray(*expected3Vec, expectedResult3);
	}

	Cryptography::HashResult actualResult1;
	Cryptography::HashResult actualResult2;
	Cryptography::HashResult actualResult3;
	Cryptography::HKDF_blake2b(
		chainingKey,
		Cryptography::DynByteSequence::fromVector(std::move(inputKeyMaterial)),
		numOutputs,
		actualResult1,
		expected2Vec.has_value() ? &actualResult2 : nullptr,
		expected3Vec.has_value() ? &actualResult3 : nullptr
	);

	EXPECT_EQ(actualResult1.raw, expectedResult1);
	if (expected2Vec.has_value())
	{
		EXPECT_EQ(actualResult2.raw, expectedResult2);
	}
	if (expected3Vec.has_value())
	{
		EXPECT_EQ(actualResult3.raw, expectedResult3);
	}
}

TEST(CryptographyHashFunctions, HashTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	testHash_blake2b(
		strToBytes("small text"),
		hexToBytes("3ff1934c76e901b66ab251e09f84061c7b35ef657556958db13c49067ee22526")
	);

	testHash_blake2b(
		strToBytes("A little bit longer text"),
		hexToBytes("49b1b70cfe74c27307292c6afecbdbbc12793e24ec1ceef6f3f2d999fc08f63e")
	);

	testHash_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		hexToBytes("88d43715d0ceab5ef5e78c94d1095a6ee252e5d8a1a567383108dfe0b3d4af09")
	);

	testHash_blake2b(
		strToBytes(""),
		hexToBytes("0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8")
	);

	testHash_blake2b(
		hexToBytes("00"),
		hexToBytes("03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314")
	);

	testHash_blake2b(
		hexToBytes("0000000000000000"),
		hexToBytes("81e47a19e6b29b0a65b9591762ce5143ed30d0261e5d24a3201752506b20f15c")
	);

	testHash_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("046c0d987075db8217087bae19e9f753305890fc6772908c57f07878211cc8cb")
	);

	testHash_blake2b(
		hexToBytes("FF"),
		hexToBytes("ac4e4076a883937282f1377ef5cacb8edd00e3c79629e43532464eb3be277367")
	);

	testHash_blake2b(
		hexToBytes("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"),
		hexToBytes("e2021160500f01190b8b9f36f9d0d1dacf8e91ae70deed6ddda43ed414585ed4")
	);

	testHash_blake2b(
		strToBytes(
			"Long long text that needs hashing, it goes on and on, continues and continues. "
			"It even spans across multiple lines, so it can fit ont screen. This text is longer than HASHLEN. "
			"And it is even longer than BLOCKLEN. This text will be put into different implementations "
			"and compared that they produce the same results."
		),
		hexToBytes("5c23931b634478aa0ca0e6fb61b90e2e8f78a0893629240b5d0b937dbcee33a3")
	);
}

TEST(CryptographyHashFunctions, HashWithContextTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b

	testHashWithContext_blake2b(
		strToBytes("test context"),
		strToBytes("test data"),
		hexToBytes("43128065e98dc7f487568ac6437db9e7fdc6d121cfa1b6cf8e9008c43d4171f3")
	);

	testHashWithContext_blake2b(
		hexToBytes("e2021160500f01190b8b9f36f9d0d1dacf8e91ae70deed6ddda43ed414585ed4"),
		strToBytes("mix data"),
		hexToBytes("22910bff1de9a9bd147089d7bb3e73db7edb219e9dc4b5d98385fee51d0fede1")
	);

	testHashWithContext_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		hexToBytes("f35293c25cbbec911339599b79e960a20b6439209c5570ef5e0607834163abf0"),
		hexToBytes("51148bb99a699a44441980cbe493dd9ecb9cee6929bb6b6d453e384848578d25")
	);
}

TEST(CryptographyHashFunctions, HmacTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b
	// test vecrtors are based on https://www.ietf.org/rfc/rfc2104.txt

	testHmac_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		strToBytes("Hi there!"),
		hexToBytes("f35293c25cbbec911339599b79e960a20b6439209c5570ef5e0607834163abf0")
	);

	testHmac_blake2b(
		// compared to the test from https://www.ietf.org/rfc/rfc2104.txt
		// we locked the function to work only with HASHLEN size of keys
		// so pad it with zeros
		strToBytes("Jefe0000000000000000000000000000"),
		strToBytes("what do ya want for nothing?"),
		hexToBytes("46259ce09762c902522c33734707ce0392dcc73b47f54da314fd72f8c89cbd86")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("09553c3e8fbaab43a0230549fefd0d33295ed0f723b0d1f5d40419b14c7d53a4")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("b2d5a1cdc52396c85d3b1ce5ce85267fe07f8c67a278bd9a74b0e793173fc34d")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("5e917f61d3b39d0a21b6e72630f2fff5fec34c3c354a3a8fdd3a1202d170d6a4")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes(""),
		hexToBytes("d1b06a3fbc3db187a60b894572b4ab52e6e16217c20a9e3f4d09eec6c0c2b22a")
	);
}

TEST(CryptographyHashFunctions, HkdfTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b
	// test vectors are based on https://datatracker.ietf.org/doc/html/rfc5869

	testHkdf_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		hexToBytes("f0f1f2f3f4f5f6f7f8f9"),
		2,
		hexToBytes("b15a3099f26e1eb312f5deb593a72f6654ee17f06aa9526220aadd98035c8d0f"),
		std::optional(hexToBytes("68d7f8c9e6a4839dd16624685c5b0063df60c91a11d1e8d4cb3d87b6ebe98244")),
		std::nullopt
	);

	testHkdf_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		hexToBytes(""),
		2,
		hexToBytes("4aba70678de6355b3e3b5b326f6fd29524b7d5ab79eaa71e20f8ba107170ce14"),
		std::optional(hexToBytes("13addecd8f6904aa048a55c3f4ec0ad81468b4c2355a3dd865f347cfdc684caf")),
		std::nullopt
	);

	testHkdf_blake2b(
		hexToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
		hexToBytes("b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"),
		3,
		hexToBytes("ddeed179dc69b56dabb2ceb2e2228f63e937f61dced5ba1b7cc47ab6f7b6d2e1"),
		std::optional(hexToBytes("df478c405c709a7a7bf12e445f77ce455bab1fdd6f8cd27796143fd062a070b5")),
		std::optional(hexToBytes("ae8c3c767f4afef01780c06d0a1d56bd9a602ea9badd09e0b6ddc2967a607bf1"))
	);
}
