// Copyright (C) Pavel Grebnev 2026
// Distributed under the MIT License (license terms are at http://opensource.org/licenses/MIT).

#include "tests/test_helper_functions.h"
#include <gtest/gtest.h>

#include "common_shared/cryptography/hash-functions.h"

static void testHmac_blake2b(const std::span<const uint8_t> keyVec, const std::span<const uint8_t> dataVec, const std::span<const uint8_t> expectedVec)
{
	Cryptography::HashResult key;
	vectorToArray(keyVec, key.raw);

	std::array<uint8_t, Cryptography::HASHLEN> expectedResult;
	vectorToArray(expectedVec, expectedResult);

	Cryptography::HashResult actualResult;
	Cryptography::HMAC_blake2b(key, dataVec, actualResult);

	EXPECT_EQ(actualResult.raw, expectedResult);
}

static void testHkdf_blake2b(const std::span<const uint8_t> chainingKeyVec, const std::span<const uint8_t> inputKeyMaterial, int numOutputs, const std::span<const uint8_t> expected1Vec, const std::optional<std::span<const uint8_t>> expected2Vec, const std::optional<std::span<const uint8_t>> expected3Vec)
{
	Cryptography::HashResult chainingKey;
	vectorToArray(chainingKeyVec, chainingKey.raw);

	std::array<uint8_t, Cryptography::HASHLEN> expectedResult1;
	vectorToArray(expected1Vec, expectedResult1);
	std::array<uint8_t, Cryptography::HASHLEN> expectedResult2;
	std::array<uint8_t, Cryptography::HASHLEN> expectedResult3;
	if (expected2Vec.has_value())
	{
		vectorToArray(*expected2Vec, expectedResult2);
	}

	if (expected3Vec.has_value())
	{
		vectorToArray(*expected3Vec, expectedResult3);
	}

	Cryptography::HashResult actualResult1;
	Cryptography::HashResult actualResult2;
	Cryptography::HashResult actualResult3;
	Cryptography::HKDF_blake2b(
		chainingKey,
		inputKeyMaterial,
		static_cast<uint8_t>(numOutputs),
		actualResult1,
		expected2Vec.has_value() ? &actualResult2 : nullptr,
		expected3Vec.has_value() ? &actualResult3 : nullptr
	);

	EXPECT_EQ(actualResult1.raw, expectedResult1);
	if (expected2Vec.has_value())
	{
		EXPECT_EQ(actualResult2.raw, expectedResult2);
	}
	if (expected3Vec.has_value())
	{
		EXPECT_EQ(actualResult3.raw, expectedResult3);
	}
}

TEST(CryptographyHashFunctions, HmacTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b
	// test vecrtors are based on https://www.ietf.org/rfc/rfc2104.txt

	testHmac_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		strToBytes("Hi there!"),
		hexToBytes("f35293c25cbbec911339599b79e960a20b6439209c5570ef5e0607834163abf0")
	);

	testHmac_blake2b(
		// compared to the test from https://www.ietf.org/rfc/rfc2104.txt
		// we locked the function to work only with HASHLEN size of keys
		// so pad it with zeros
		strToBytes("Jefe0000000000000000000000000000"),
		strToBytes("what do ya want for nothing?"),
		hexToBytes("46259ce09762c902522c33734707ce0392dcc73b47f54da314fd72f8c89cbd86")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("09553c3e8fbaab43a0230549fefd0d33295ed0f723b0d1f5d40419b14c7d53a4")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("b2d5a1cdc52396c85d3b1ce5ce85267fe07f8c67a278bd9a74b0e793173fc34d")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes("DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"),
		hexToBytes("5e917f61d3b39d0a21b6e72630f2fff5fec34c3c354a3a8fdd3a1202d170d6a4")
	);

	testHmac_blake2b(
		hexToBytes("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"),
		hexToBytes(""),
		hexToBytes("d1b06a3fbc3db187a60b894572b4ab52e6e16217c20a9e3f4d09eec6c0c2b22a")
	);
}

TEST(CryptographyHashFunctions, HkdfTests)
{
	// the results are taken from the reference Rust implementation generated by noiseexplorer.com
	// where Blake2s replaced with Blake2b
	// test vectors are based on https://datatracker.ietf.org/doc/html/rfc5869

	testHkdf_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		hexToBytes("f0f1f2f3f4f5f6f7f8f9"),
		2,
		hexToBytes("b15a3099f26e1eb312f5deb593a72f6654ee17f06aa9526220aadd98035c8d0f"),
		std::optional(hexToBytes("68d7f8c9e6a4839dd16624685c5b0063df60c91a11d1e8d4cb3d87b6ebe98244")),
		std::nullopt
	);

	testHkdf_blake2b(
		hexToBytes("0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"),
		hexToBytes(""),
		2,
		hexToBytes("4aba70678de6355b3e3b5b326f6fd29524b7d5ab79eaa71e20f8ba107170ce14"),
		std::optional(hexToBytes("13addecd8f6904aa048a55c3f4ec0ad81468b4c2355a3dd865f347cfdc684caf")),
		std::nullopt
	);

	testHkdf_blake2b(
		hexToBytes("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"),
		hexToBytes("b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"),
		3,
		hexToBytes("ddeed179dc69b56dabb2ceb2e2228f63e937f61dced5ba1b7cc47ab6f7b6d2e1"),
		std::optional(hexToBytes("df478c405c709a7a7bf12e445f77ce455bab1fdd6f8cd27796143fd062a070b5")),
		std::optional(hexToBytes("ae8c3c767f4afef01780c06d0a1d56bd9a602ea9badd09e0b6ddc2967a607bf1"))
	);
}
